# Generated by Django 5.0.2 on 2024-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_facedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
