# Generated by Django 5.0.2 on 2024-05-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_facedata_landmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password2',
        ),
        migrations.AlterField(
            model_name='facedata',
            name='name',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
