# Generated by Django 5.0.2 on 2024-05-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_password_user_password2_alter_facedata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
