# Generated by Django 5.0.2 on 2024-05-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_facedata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedata',
            name='password',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
