# Generated by Django 5.0.2 on 2024-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_facedata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
