# Generated by Django 5.0.2 on 2024-05-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_facedata_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password2',
            new_name='password',
        ),
    ]
