# Generated by Django 5.0.2 on 2024-05-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_user_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='username',
            new_name='username1',
        ),
    ]
