# Generated by Django 5.0.2 on 2024-05-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_email_user1_email1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='username1',
            new_name='username',
        ),
    ]
