# Generated by Django 5.0.2 on 2024-05-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='password',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
