# Generated by Django 5.0.2 on 2024-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_password_teacher_name_remove_teacher_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('present', models.BooleanField()),
            ],
        ),
    ]
