# Generated by Django 5.0.2 on 2024-05-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_presenty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenty',
            name='present',
        ),
    ]
