# Generated by Django 5.0.2 on 2024-05-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_presenty_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenty',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
