# Generated by Django 5.0.2 on 2024-05-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_deviceipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceIPAddress',
        ),
    ]
