# Generated by Django 5.0.2 on 2024-04-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_log_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDAta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarks', models.TextField()),
            ],
        ),
    ]
